const preguntasJSON = [
    { nombre: "farmacia 💊", respuesta: "drugstore" },
    { nombre: "farmacia 💊", respuesta: "pharmacy" },
    { nombre: "oficina de correo 📮", respuesta: "post office" },
    { nombre: "polideportivo ⚽", respuesta: "sport center" },
    { nombre: "gimnasio 💪", respuesta: "gym" },
    { nombre: "estadio 🏟️", respuesta: "stadium" },
    { nombre: "piscina 🏊", respuesta: "swimming pool" },
    { nombre: "gasolinera ⛽", respuesta: "petrol station" },
    { nombre: "parque 🌳", respuesta: "park" },
    { nombre: "patio de juegos 🎪", respuesta: "playground" },
    { nombre: "pueblo 🏘️", respuesta: "village" },
    { nombre: "ciudad 🏙️", respuesta: "town" },
    { nombre: "ciudad 🏙️", respuesta: "city" },
    { nombre: "aparcamiento 🅿️", respuesta: "car park" },
    { nombre: "aparcamiento 🅿️", respuesta: "parking" },
    { nombre: "autopista 🛣️", respuesta: "motorway" },
    { nombre: "carretera 🛣️", respuesta: "highway" },
    { nombre: "oficina de reservas 🎫", respuesta: "booking office" },
    { nombre: "reservar 📝", respuesta: "to book" },
    { nombre: "entradas 🎫", respuesta: "tickets" },
    { nombre: "acera 🚶", respuesta: "pavement" },
    { nombre: "paso de peatones 🚸", respuesta: "pedestrian cross" },
    { nombre: "cebra 🦓", respuesta: "pedestrian cross" },
    { nombre: "viajar ✈️", respuesta: "travel" },
    { nombre: "viaje 🧳", respuesta: "trip" },
    { nombre: "viaje 🧳", respuesta: "journey" },
    { nombre: "estación de policía 🚔", respuesta: "police station" },
    { nombre: "parque de bomberos 🚒", respuesta: "fire station" },
    { nombre: "estación de tren 🚂", respuesta: "railway station" },
    { nombre: "teatro 🎭", respuesta: "theatre" },
    { nombre: "centro de la ciudad 🏙️", respuesta: "city centre" },
    { nombre: "información turística ℹ️", respuesta: "tourist information" },
    { nombre: "aeropuerto ✈️", respuesta: "airport" },
    { nombre: "puerto ⚓", respuesta: "harbour" },
    { nombre: "estación 🚉", respuesta: "station" },
    { nombre: "esquina 📐", respuesta: "corner" },
    { nombre: "el metro 🚇", respuesta: "underground" },
    { nombre: "metro 🚇", respuesta: "metro" },
    { nombre: "metro 🚇", respuesta: "tube" },
    { nombre: "metro 🚇", respuesta: "subway" },
    { nombre: "señal 🪧", respuesta: "signpost" },
    { nombre: "señal de tráfico 🚦", respuesta: "traffic signal" },
    { nombre: "banco 🏦", respuesta: "bank" },
    { nombre: "cajero automático 💳", respuesta: "cash machine" },
    { nombre: "pasajero 🧳", respuesta: "passenger" },
    { nombre: "visitante 👋", respuesta: "visitor" },
    { nombre: "crucero 🚢", respuesta: "cruise" },
    { nombre: "tour 🗺️", respuesta: "tour" },
    { nombre: "monumentos 🗿", respuesta: "monuments" },
    { nombre: "torres 🗼", respuesta: "towers" },
    { nombre: "hacer turismo 📸", respuesta: "sightseeing" },
    { nombre: "museo 🏛️", respuesta: "museum" },
    { nombre: "galería 🖼️", respuesta: "gallery" },
    { nombre: "colección 🎨", respuesta: "collection" },
    { nombre: "horario de apertura 🕐", respuesta: "opening hours" },
    { nombre: "inauguración de casa 🏠", respuesta: "opening hours" },
    { nombre: "edificio 🏢", respuesta: "building" },
    { nombre: "entrada 🚪", respuesta: "entrance" },
    { nombre: "salida 🚪", respuesta: "exit" },
    { nombre: "portón 🚧", respuesta: "gate" },
    { nombre: "casa 🏠", respuesta: "house" },
    { nombre: "piso 🏢", respuesta: "flat" },
    { nombre: "apartamento 🏢", respuesta: "flat" },
    { nombre: "apartamento 🏢", respuesta: "apartment" },
    { nombre: "bloque de viviendas 🏢", respuesta: "block" },
    { nombre: "manzana 🍎", respuesta: "block" },
    { nombre: "zoo 🦁", respuesta: "zoo" },
    { nombre: "hotel 🏨", respuesta: "hotel" },
    { nombre: "hostal 🏨", respuesta: "hostel" },
    { nombre: "farolas 💡", respuesta: "streetlight" },
    { nombre: "rascacielos 🏙️", respuesta: "skyscraper" },
    { nombre: "restaurante 🍽️", respuesta: "restaurant" },
    { nombre: "cafetería ☕", respuesta: "café" },
    { nombre: "café ☕", respuesta: "coffee" },
    { nombre: "colegio 🏫", respuesta: "school" },
    { nombre: "colegio universitario 🎓", respuesta: "college" },
    { nombre: "universidad 🎓", respuesta: "university" },
    { nombre: "ascensor 🛗", respuesta: "elevator" },
    { nombre: "ascensor 🛗", respuesta: "lift" },
    { nombre: "garaje 🚗", respuesta: "garage" },
    { nombre: "mercado 🛒", respuesta: "market" },
    { nombre: "supermercado 🛒", respuesta: "supermarket" },
    { nombre: "mercadillo 🏪", respuesta: "street market" },
    { nombre: "lugares 📍", respuesta: "places" },
    { nombre: "esculturas 🗿", respuesta: "sculptures" },
    { nombre: "festival 🎉", respuesta: "festival" },
    { nombre: "visitar 👀", respuesta: "visit" },
    { nombre: "palacio 🏰", respuesta: "palace" },
    { nombre: "castillo 🏰", respuesta: "castle" },
    { nombre: "grandes almacenes 🏬", respuesta: "department store" },
    { nombre: "plaza 🏛️", respuesta: "square" },
    { nombre: "calle 🛣️", respuesta: "street" },
    { nombre: "camino 🛣️", respuesta: "road" },
    { nombre: "carretera 🛣️", respuesta: "road" },
    { nombre: "calle 🛣️", respuesta: "road" },
    { nombre: "rotonda ⭕", respuesta: "roundabout" },
    { nombre: "habitación 🛏️", respuesta: "room" },
    { nombre: "techo 🏠", respuesta: "roof" },
    { nombre: "tejado 🏠", respuesta: "roof" },
    { nombre: "piso (edificio) 🏢", respuesta: "floor" },
    { nombre: "suelo (edificio) 🏢", respuesta: "floor" },
    { nombre: "planta (edificio) 🏢", respuesta: "floor" },
    { nombre: "puente 🌉", respuesta: "bridge" },
    { nombre: "dirección 📍", respuesta: "address" },
    { nombre: "librería 📚", respuesta: "bookstore" },
    { nombre: "librería 📚", respuesta: "bookshop" },
    { nombre: "cine 🎬", respuesta: "cinema" },
    { nombre: "discoteca 💃", respuesta: "disco" },
    { nombre: "pub 🍺", respuesta: "pub" },
    { nombre: "bar 🍺", respuesta: "bar" },
    { nombre: "fábrica 🏭", respuesta: "factory" },
    { nombre: "oficina 🏢", respuesta: "office" },
    { nombre: "tienda de comestibles 🛒", respuesta: "grocery-store" },
    { nombre: "hospital 🏥", respuesta: "hospital" }
];

const tituloJuego = "6pri-Ingles Unit 8 Vocabulary"; // Título del juego
const prefijoPregunta = "Traduce "; // Prefijo de la pregunta 
const sufijoPregunta = " al inglés"; // Sufijo de la pregunta
const curso = "6º Primaria";
const descripcion = "Vocabulario de la Unidad 8: Ciudades Bonitas y Lugares";
const tipoJuego = "preguntas"; // Puede ser "preguntas", "preguntaRespuesta", "completarVector", "tablaperiodica" o "Formulacion"

